/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as InputsRouteImport } from './routes/inputs'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as FarmersRouteImport } from './routes/farmers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmersIndexRouteImport } from './routes/farmers.index'
import { Route as FarmersIdRouteImport } from './routes/farmers.$id'

const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InputsRoute = InputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersRoute = FarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersIndexRoute = FarmersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmersRoute,
} as any)
const FarmersIdRoute = FarmersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FarmersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/farmers': typeof FarmersRouteWithChildren
  '/follow-ups': typeof FollowUpsRoute
  '/inputs': typeof InputsRoute
  '/intelligence': typeof IntelligenceRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/visits': typeof VisitsRoute
  '/farmers/$id': typeof FarmersIdRoute
  '/farmers/': typeof FarmersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/inputs': typeof InputsRoute
  '/intelligence': typeof IntelligenceRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/visits': typeof VisitsRoute
  '/farmers/$id': typeof FarmersIdRoute
  '/farmers': typeof FarmersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/farmers': typeof FarmersRouteWithChildren
  '/follow-ups': typeof FollowUpsRoute
  '/inputs': typeof InputsRoute
  '/intelligence': typeof IntelligenceRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/visits': typeof VisitsRoute
  '/farmers/$id': typeof FarmersIdRoute
  '/farmers/': typeof FarmersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/farmers'
    | '/follow-ups'
    | '/inputs'
    | '/intelligence'
    | '/recommendations'
    | '/settings'
    | '/signup'
    | '/visits'
    | '/farmers/$id'
    | '/farmers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/follow-ups'
    | '/inputs'
    | '/intelligence'
    | '/recommendations'
    | '/settings'
    | '/signup'
    | '/visits'
    | '/farmers/$id'
    | '/farmers'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/farmers'
    | '/follow-ups'
    | '/inputs'
    | '/intelligence'
    | '/recommendations'
    | '/settings'
    | '/signup'
    | '/visits'
    | '/farmers/$id'
    | '/farmers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  FarmersRoute: typeof FarmersRouteWithChildren
  FollowUpsRoute: typeof FollowUpsRoute
  InputsRoute: typeof InputsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VisitsRoute: typeof VisitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputs': {
      id: '/inputs'
      path: '/inputs'
      fullPath: '/inputs'
      preLoaderRoute: typeof InputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers': {
      id: '/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof FarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/': {
      id: '/farmers/'
      path: '/'
      fullPath: '/farmers/'
      preLoaderRoute: typeof FarmersIndexRouteImport
      parentRoute: typeof FarmersRoute
    }
    '/farmers/$id': {
      id: '/farmers/$id'
      path: '/$id'
      fullPath: '/farmers/$id'
      preLoaderRoute: typeof FarmersIdRouteImport
      parentRoute: typeof FarmersRoute
    }
  }
}

interface FarmersRouteChildren {
  FarmersIdRoute: typeof FarmersIdRoute
  FarmersIndexRoute: typeof FarmersIndexRoute
}

const FarmersRouteChildren: FarmersRouteChildren = {
  FarmersIdRoute: FarmersIdRoute,
  FarmersIndexRoute: FarmersIndexRoute,
}

const FarmersRouteWithChildren =
  FarmersRoute._addFileChildren(FarmersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  FarmersRoute: FarmersRouteWithChildren,
  FollowUpsRoute: FollowUpsRoute,
  InputsRoute: InputsRoute,
  IntelligenceRoute: IntelligenceRoute,
  RecommendationsRoute: RecommendationsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VisitsRoute: VisitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
